// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db.proto

package protocol;

public final class DB {
  private DB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code DB.ChannelType}
   */
  public enum ChannelType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Invalid = 0;</code>
     */
    Invalid(0, 0),
    /**
     * <code>Joy7 = 17;</code>
     */
    Joy7(1, 17),
    ;

    /**
     * <code>Invalid = 0;</code>
     */
    public static final int Invalid_VALUE = 0;
    /**
     * <code>Joy7 = 17;</code>
     */
    public static final int Joy7_VALUE = 17;


    public final int getNumber() { return value; }

    public static ChannelType valueOf(int value) {
      switch (value) {
        case 0: return Invalid;
        case 17: return Joy7;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ChannelType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ChannelType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ChannelType>() {
            public ChannelType findValueByNumber(int number) {
              return ChannelType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protocol.DB.getDescriptor().getEnumTypes().get(0);
    }

    private static final ChannelType[] VALUES = values();

    public static ChannelType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ChannelType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:DB.ChannelType)
  }

  public interface Tbl_UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DB.Tbl_User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 uid = 1;</code>
     *
     * <pre>
     * user id 64 bit
     * </pre>
     */
    boolean hasUid();
    /**
     * <code>required int64 uid = 1;</code>
     *
     * <pre>
     * user id 64 bit
     * </pre>
     */
    long getUid();

    /**
     * <code>required int32 channel = 2;</code>
     *
     * <pre>
     * channel
     * </pre>
     */
    boolean hasChannel();
    /**
     * <code>required int32 channel = 2;</code>
     *
     * <pre>
     * channel
     * </pre>
     */
    int getChannel();

    /**
     * <code>required uint64 registerTime = 3;</code>
     *
     * <pre>
     * register time
     * </pre>
     */
    boolean hasRegisterTime();
    /**
     * <code>required uint64 registerTime = 3;</code>
     *
     * <pre>
     * register time
     * </pre>
     */
    long getRegisterTime();

    /**
     * <code>required uint64 lastLoginTime = 4;</code>
     *
     * <pre>
     * last login time
     * </pre>
     */
    boolean hasLastLoginTime();
    /**
     * <code>required uint64 lastLoginTime = 4;</code>
     *
     * <pre>
     * last login time
     * </pre>
     */
    long getLastLoginTime();

    /**
     * <code>required uint32 loginTimes = 5;</code>
     *
     * <pre>
     * login times
     * </pre>
     */
    boolean hasLoginTimes();
    /**
     * <code>required uint32 loginTimes = 5;</code>
     *
     * <pre>
     * login times
     * </pre>
     */
    int getLoginTimes();

    /**
     * <code>required bool isLogin = 6;</code>
     *
     * <pre>
     * login times
     * </pre>
     */
    boolean hasIsLogin();
    /**
     * <code>required bool isLogin = 6;</code>
     *
     * <pre>
     * login times
     * </pre>
     */
    boolean getIsLogin();

    /**
     * <code>required double money1 = 7;</code>
     *
     * <pre>
     * login times
     * </pre>
     */
    boolean hasMoney1();
    /**
     * <code>required double money1 = 7;</code>
     *
     * <pre>
     * login times
     * </pre>
     */
    double getMoney1();

    /**
     * <code>required float money2 = 8;</code>
     *
     * <pre>
     * login times
     * </pre>
     */
    boolean hasMoney2();
    /**
     * <code>required float money2 = 8;</code>
     *
     * <pre>
     * login times
     * </pre>
     */
    float getMoney2();

    /**
     * <code>required string msg = 9;</code>
     *
     * <pre>
     * login times
     * </pre>
     */
    boolean hasMsg();
    /**
     * <code>required string msg = 9;</code>
     *
     * <pre>
     * login times
     * </pre>
     */
    java.lang.String getMsg();
    /**
     * <code>required string msg = 9;</code>
     *
     * <pre>
     * login times
     * </pre>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>required bytes byteMsg = 10;</code>
     *
     * <pre>
     * login times
     * </pre>
     */
    boolean hasByteMsg();
    /**
     * <code>required bytes byteMsg = 10;</code>
     *
     * <pre>
     * login times
     * </pre>
     */
    com.google.protobuf.ByteString getByteMsg();
  }
  /**
   * Protobuf type {@code DB.Tbl_User}
   */
  public static final class Tbl_User extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:DB.Tbl_User)
      Tbl_UserOrBuilder {
    // Use Tbl_User.newBuilder() to construct.
    private Tbl_User(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Tbl_User(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Tbl_User defaultInstance;
    public static Tbl_User getDefaultInstance() {
      return defaultInstance;
    }

    public Tbl_User getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Tbl_User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              uid_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              channel_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              registerTime_ = input.readUInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              lastLoginTime_ = input.readUInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              loginTimes_ = input.readUInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              isLogin_ = input.readBool();
              break;
            }
            case 57: {
              bitField0_ |= 0x00000040;
              money1_ = input.readDouble();
              break;
            }
            case 69: {
              bitField0_ |= 0x00000080;
              money2_ = input.readFloat();
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              msg_ = bs;
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              byteMsg_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.DB.internal_static_DB_Tbl_User_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.DB.internal_static_DB_Tbl_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.DB.Tbl_User.class, protocol.DB.Tbl_User.Builder.class);
    }

    public static com.google.protobuf.Parser<Tbl_User> PARSER =
        new com.google.protobuf.AbstractParser<Tbl_User>() {
      public Tbl_User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Tbl_User(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Tbl_User> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int UID_FIELD_NUMBER = 1;
    private long uid_;
    /**
     * <code>required int64 uid = 1;</code>
     *
     * <pre>
     * user id 64 bit
     * </pre>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 uid = 1;</code>
     *
     * <pre>
     * user id 64 bit
     * </pre>
     */
    public long getUid() {
      return uid_;
    }

    public static final int CHANNEL_FIELD_NUMBER = 2;
    private int channel_;
    /**
     * <code>required int32 channel = 2;</code>
     *
     * <pre>
     * channel
     * </pre>
     */
    public boolean hasChannel() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 channel = 2;</code>
     *
     * <pre>
     * channel
     * </pre>
     */
    public int getChannel() {
      return channel_;
    }

    public static final int REGISTERTIME_FIELD_NUMBER = 3;
    private long registerTime_;
    /**
     * <code>required uint64 registerTime = 3;</code>
     *
     * <pre>
     * register time
     * </pre>
     */
    public boolean hasRegisterTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint64 registerTime = 3;</code>
     *
     * <pre>
     * register time
     * </pre>
     */
    public long getRegisterTime() {
      return registerTime_;
    }

    public static final int LASTLOGINTIME_FIELD_NUMBER = 4;
    private long lastLoginTime_;
    /**
     * <code>required uint64 lastLoginTime = 4;</code>
     *
     * <pre>
     * last login time
     * </pre>
     */
    public boolean hasLastLoginTime() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required uint64 lastLoginTime = 4;</code>
     *
     * <pre>
     * last login time
     * </pre>
     */
    public long getLastLoginTime() {
      return lastLoginTime_;
    }

    public static final int LOGINTIMES_FIELD_NUMBER = 5;
    private int loginTimes_;
    /**
     * <code>required uint32 loginTimes = 5;</code>
     *
     * <pre>
     * login times
     * </pre>
     */
    public boolean hasLoginTimes() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required uint32 loginTimes = 5;</code>
     *
     * <pre>
     * login times
     * </pre>
     */
    public int getLoginTimes() {
      return loginTimes_;
    }

    public static final int ISLOGIN_FIELD_NUMBER = 6;
    private boolean isLogin_;
    /**
     * <code>required bool isLogin = 6;</code>
     *
     * <pre>
     * login times
     * </pre>
     */
    public boolean hasIsLogin() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required bool isLogin = 6;</code>
     *
     * <pre>
     * login times
     * </pre>
     */
    public boolean getIsLogin() {
      return isLogin_;
    }

    public static final int MONEY1_FIELD_NUMBER = 7;
    private double money1_;
    /**
     * <code>required double money1 = 7;</code>
     *
     * <pre>
     * login times
     * </pre>
     */
    public boolean hasMoney1() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required double money1 = 7;</code>
     *
     * <pre>
     * login times
     * </pre>
     */
    public double getMoney1() {
      return money1_;
    }

    public static final int MONEY2_FIELD_NUMBER = 8;
    private float money2_;
    /**
     * <code>required float money2 = 8;</code>
     *
     * <pre>
     * login times
     * </pre>
     */
    public boolean hasMoney2() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required float money2 = 8;</code>
     *
     * <pre>
     * login times
     * </pre>
     */
    public float getMoney2() {
      return money2_;
    }

    public static final int MSG_FIELD_NUMBER = 9;
    private java.lang.Object msg_;
    /**
     * <code>required string msg = 9;</code>
     *
     * <pre>
     * login times
     * </pre>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required string msg = 9;</code>
     *
     * <pre>
     * login times
     * </pre>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string msg = 9;</code>
     *
     * <pre>
     * login times
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BYTEMSG_FIELD_NUMBER = 10;
    private com.google.protobuf.ByteString byteMsg_;
    /**
     * <code>required bytes byteMsg = 10;</code>
     *
     * <pre>
     * login times
     * </pre>
     */
    public boolean hasByteMsg() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>required bytes byteMsg = 10;</code>
     *
     * <pre>
     * login times
     * </pre>
     */
    public com.google.protobuf.ByteString getByteMsg() {
      return byteMsg_;
    }

    private void initFields() {
      uid_ = 0L;
      channel_ = 0;
      registerTime_ = 0L;
      lastLoginTime_ = 0L;
      loginTimes_ = 0;
      isLogin_ = false;
      money1_ = 0D;
      money2_ = 0F;
      msg_ = "";
      byteMsg_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChannel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRegisterTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLastLoginTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLoginTimes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsLogin()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMoney1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMoney2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasByteMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, channel_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(3, registerTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt64(4, lastLoginTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, loginTimes_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(6, isLogin_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeDouble(7, money1_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeFloat(8, money2_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getMsgBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, byteMsg_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, uid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, channel_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, registerTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, lastLoginTime_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, loginTimes_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, isLogin_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, money1_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, money2_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getMsgBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, byteMsg_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static protocol.DB.Tbl_User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.DB.Tbl_User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.DB.Tbl_User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.DB.Tbl_User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.DB.Tbl_User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.DB.Tbl_User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static protocol.DB.Tbl_User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static protocol.DB.Tbl_User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static protocol.DB.Tbl_User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static protocol.DB.Tbl_User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protocol.DB.Tbl_User prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DB.Tbl_User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DB.Tbl_User)
        protocol.DB.Tbl_UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.DB.internal_static_DB_Tbl_User_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.DB.internal_static_DB_Tbl_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.DB.Tbl_User.class, protocol.DB.Tbl_User.Builder.class);
      }

      // Construct using protocol.DB.Tbl_User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        channel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        registerTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        lastLoginTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        loginTimes_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        isLogin_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        money1_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000040);
        money2_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000080);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        byteMsg_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.DB.internal_static_DB_Tbl_User_descriptor;
      }

      public protocol.DB.Tbl_User getDefaultInstanceForType() {
        return protocol.DB.Tbl_User.getDefaultInstance();
      }

      public protocol.DB.Tbl_User build() {
        protocol.DB.Tbl_User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.DB.Tbl_User buildPartial() {
        protocol.DB.Tbl_User result = new protocol.DB.Tbl_User(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.channel_ = channel_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.registerTime_ = registerTime_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.lastLoginTime_ = lastLoginTime_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.loginTimes_ = loginTimes_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.isLogin_ = isLogin_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.money1_ = money1_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.money2_ = money2_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.msg_ = msg_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.byteMsg_ = byteMsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.DB.Tbl_User) {
          return mergeFrom((protocol.DB.Tbl_User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.DB.Tbl_User other) {
        if (other == protocol.DB.Tbl_User.getDefaultInstance()) return this;
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasChannel()) {
          setChannel(other.getChannel());
        }
        if (other.hasRegisterTime()) {
          setRegisterTime(other.getRegisterTime());
        }
        if (other.hasLastLoginTime()) {
          setLastLoginTime(other.getLastLoginTime());
        }
        if (other.hasLoginTimes()) {
          setLoginTimes(other.getLoginTimes());
        }
        if (other.hasIsLogin()) {
          setIsLogin(other.getIsLogin());
        }
        if (other.hasMoney1()) {
          setMoney1(other.getMoney1());
        }
        if (other.hasMoney2()) {
          setMoney2(other.getMoney2());
        }
        if (other.hasMsg()) {
          bitField0_ |= 0x00000100;
          msg_ = other.msg_;
          onChanged();
        }
        if (other.hasByteMsg()) {
          setByteMsg(other.getByteMsg());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUid()) {
          
          return false;
        }
        if (!hasChannel()) {
          
          return false;
        }
        if (!hasRegisterTime()) {
          
          return false;
        }
        if (!hasLastLoginTime()) {
          
          return false;
        }
        if (!hasLoginTimes()) {
          
          return false;
        }
        if (!hasIsLogin()) {
          
          return false;
        }
        if (!hasMoney1()) {
          
          return false;
        }
        if (!hasMoney2()) {
          
          return false;
        }
        if (!hasMsg()) {
          
          return false;
        }
        if (!hasByteMsg()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.DB.Tbl_User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.DB.Tbl_User) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long uid_ ;
      /**
       * <code>required int64 uid = 1;</code>
       *
       * <pre>
       * user id 64 bit
       * </pre>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 uid = 1;</code>
       *
       * <pre>
       * user id 64 bit
       * </pre>
       */
      public long getUid() {
        return uid_;
      }
      /**
       * <code>required int64 uid = 1;</code>
       *
       * <pre>
       * user id 64 bit
       * </pre>
       */
      public Builder setUid(long value) {
        bitField0_ |= 0x00000001;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 uid = 1;</code>
       *
       * <pre>
       * user id 64 bit
       * </pre>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uid_ = 0L;
        onChanged();
        return this;
      }

      private int channel_ ;
      /**
       * <code>required int32 channel = 2;</code>
       *
       * <pre>
       * channel
       * </pre>
       */
      public boolean hasChannel() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 channel = 2;</code>
       *
       * <pre>
       * channel
       * </pre>
       */
      public int getChannel() {
        return channel_;
      }
      /**
       * <code>required int32 channel = 2;</code>
       *
       * <pre>
       * channel
       * </pre>
       */
      public Builder setChannel(int value) {
        bitField0_ |= 0x00000002;
        channel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 channel = 2;</code>
       *
       * <pre>
       * channel
       * </pre>
       */
      public Builder clearChannel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        channel_ = 0;
        onChanged();
        return this;
      }

      private long registerTime_ ;
      /**
       * <code>required uint64 registerTime = 3;</code>
       *
       * <pre>
       * register time
       * </pre>
       */
      public boolean hasRegisterTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint64 registerTime = 3;</code>
       *
       * <pre>
       * register time
       * </pre>
       */
      public long getRegisterTime() {
        return registerTime_;
      }
      /**
       * <code>required uint64 registerTime = 3;</code>
       *
       * <pre>
       * register time
       * </pre>
       */
      public Builder setRegisterTime(long value) {
        bitField0_ |= 0x00000004;
        registerTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 registerTime = 3;</code>
       *
       * <pre>
       * register time
       * </pre>
       */
      public Builder clearRegisterTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        registerTime_ = 0L;
        onChanged();
        return this;
      }

      private long lastLoginTime_ ;
      /**
       * <code>required uint64 lastLoginTime = 4;</code>
       *
       * <pre>
       * last login time
       * </pre>
       */
      public boolean hasLastLoginTime() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required uint64 lastLoginTime = 4;</code>
       *
       * <pre>
       * last login time
       * </pre>
       */
      public long getLastLoginTime() {
        return lastLoginTime_;
      }
      /**
       * <code>required uint64 lastLoginTime = 4;</code>
       *
       * <pre>
       * last login time
       * </pre>
       */
      public Builder setLastLoginTime(long value) {
        bitField0_ |= 0x00000008;
        lastLoginTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 lastLoginTime = 4;</code>
       *
       * <pre>
       * last login time
       * </pre>
       */
      public Builder clearLastLoginTime() {
        bitField0_ = (bitField0_ & ~0x00000008);
        lastLoginTime_ = 0L;
        onChanged();
        return this;
      }

      private int loginTimes_ ;
      /**
       * <code>required uint32 loginTimes = 5;</code>
       *
       * <pre>
       * login times
       * </pre>
       */
      public boolean hasLoginTimes() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required uint32 loginTimes = 5;</code>
       *
       * <pre>
       * login times
       * </pre>
       */
      public int getLoginTimes() {
        return loginTimes_;
      }
      /**
       * <code>required uint32 loginTimes = 5;</code>
       *
       * <pre>
       * login times
       * </pre>
       */
      public Builder setLoginTimes(int value) {
        bitField0_ |= 0x00000010;
        loginTimes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 loginTimes = 5;</code>
       *
       * <pre>
       * login times
       * </pre>
       */
      public Builder clearLoginTimes() {
        bitField0_ = (bitField0_ & ~0x00000010);
        loginTimes_ = 0;
        onChanged();
        return this;
      }

      private boolean isLogin_ ;
      /**
       * <code>required bool isLogin = 6;</code>
       *
       * <pre>
       * login times
       * </pre>
       */
      public boolean hasIsLogin() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required bool isLogin = 6;</code>
       *
       * <pre>
       * login times
       * </pre>
       */
      public boolean getIsLogin() {
        return isLogin_;
      }
      /**
       * <code>required bool isLogin = 6;</code>
       *
       * <pre>
       * login times
       * </pre>
       */
      public Builder setIsLogin(boolean value) {
        bitField0_ |= 0x00000020;
        isLogin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isLogin = 6;</code>
       *
       * <pre>
       * login times
       * </pre>
       */
      public Builder clearIsLogin() {
        bitField0_ = (bitField0_ & ~0x00000020);
        isLogin_ = false;
        onChanged();
        return this;
      }

      private double money1_ ;
      /**
       * <code>required double money1 = 7;</code>
       *
       * <pre>
       * login times
       * </pre>
       */
      public boolean hasMoney1() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required double money1 = 7;</code>
       *
       * <pre>
       * login times
       * </pre>
       */
      public double getMoney1() {
        return money1_;
      }
      /**
       * <code>required double money1 = 7;</code>
       *
       * <pre>
       * login times
       * </pre>
       */
      public Builder setMoney1(double value) {
        bitField0_ |= 0x00000040;
        money1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double money1 = 7;</code>
       *
       * <pre>
       * login times
       * </pre>
       */
      public Builder clearMoney1() {
        bitField0_ = (bitField0_ & ~0x00000040);
        money1_ = 0D;
        onChanged();
        return this;
      }

      private float money2_ ;
      /**
       * <code>required float money2 = 8;</code>
       *
       * <pre>
       * login times
       * </pre>
       */
      public boolean hasMoney2() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required float money2 = 8;</code>
       *
       * <pre>
       * login times
       * </pre>
       */
      public float getMoney2() {
        return money2_;
      }
      /**
       * <code>required float money2 = 8;</code>
       *
       * <pre>
       * login times
       * </pre>
       */
      public Builder setMoney2(float value) {
        bitField0_ |= 0x00000080;
        money2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float money2 = 8;</code>
       *
       * <pre>
       * login times
       * </pre>
       */
      public Builder clearMoney2() {
        bitField0_ = (bitField0_ & ~0x00000080);
        money2_ = 0F;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>required string msg = 9;</code>
       *
       * <pre>
       * login times
       * </pre>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required string msg = 9;</code>
       *
       * <pre>
       * login times
       * </pre>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string msg = 9;</code>
       *
       * <pre>
       * login times
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string msg = 9;</code>
       *
       * <pre>
       * login times
       * </pre>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string msg = 9;</code>
       *
       * <pre>
       * login times
       * </pre>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000100);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>required string msg = 9;</code>
       *
       * <pre>
       * login times
       * </pre>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        msg_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString byteMsg_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes byteMsg = 10;</code>
       *
       * <pre>
       * login times
       * </pre>
       */
      public boolean hasByteMsg() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>required bytes byteMsg = 10;</code>
       *
       * <pre>
       * login times
       * </pre>
       */
      public com.google.protobuf.ByteString getByteMsg() {
        return byteMsg_;
      }
      /**
       * <code>required bytes byteMsg = 10;</code>
       *
       * <pre>
       * login times
       * </pre>
       */
      public Builder setByteMsg(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        byteMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes byteMsg = 10;</code>
       *
       * <pre>
       * login times
       * </pre>
       */
      public Builder clearByteMsg() {
        bitField0_ = (bitField0_ & ~0x00000200);
        byteMsg_ = getDefaultInstance().getByteMsg();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:DB.Tbl_User)
    }

    static {
      defaultInstance = new Tbl_User(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:DB.Tbl_User)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DB_Tbl_User_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_DB_Tbl_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010db.proto\022\002DB\"\270\001\n\010Tbl_User\022\013\n\003uid\030\001 \002(\003" +
      "\022\017\n\007channel\030\002 \002(\005\022\024\n\014registerTime\030\003 \002(\004\022" +
      "\025\n\rlastLoginTime\030\004 \002(\004\022\022\n\nloginTimes\030\005 \002" +
      "(\r\022\017\n\007isLogin\030\006 \002(\010\022\016\n\006money1\030\007 \002(\001\022\016\n\006m" +
      "oney2\030\010 \002(\002\022\013\n\003msg\030\t \002(\t\022\017\n\007byteMsg\030\n \002(" +
      "\014*$\n\013ChannelType\022\013\n\007Invalid\020\000\022\010\n\004Joy7\020\021B" +
      "\016\n\010protocolB\002DB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_DB_Tbl_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DB_Tbl_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_DB_Tbl_User_descriptor,
        new java.lang.String[] { "Uid", "Channel", "RegisterTime", "LastLoginTime", "LoginTimes", "IsLogin", "Money1", "Money2", "Msg", "ByteMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
