# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: db.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='db.proto',
  package='DB',
  serialized_pb=_b('\n\x08\x64\x62.proto\x12\x02\x44\x42\"\xb8\x01\n\x08Tbl_User\x12\x0b\n\x03uid\x18\x01 \x02(\x03\x12\x0f\n\x07\x63hannel\x18\x02 \x02(\x05\x12\x14\n\x0cregisterTime\x18\x03 \x02(\x04\x12\x15\n\rlastLoginTime\x18\x04 \x02(\x04\x12\x12\n\nloginTimes\x18\x05 \x02(\r\x12\x0f\n\x07isLogin\x18\x06 \x02(\x08\x12\x0e\n\x06money1\x18\x07 \x02(\x01\x12\x0e\n\x06money2\x18\x08 \x02(\x02\x12\x0b\n\x03msg\x18\t \x02(\t\x12\x0f\n\x07\x62yteMsg\x18\n \x02(\x0c*$\n\x0b\x43hannelType\x12\x0b\n\x07Invalid\x10\x00\x12\x08\n\x04Joy7\x10\x11\x42\x0e\n\x08protocolB\x02\x44\x42')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_CHANNELTYPE = _descriptor.EnumDescriptor(
  name='ChannelType',
  full_name='DB.ChannelType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Invalid', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Joy7', index=1, number=17,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=203,
  serialized_end=239,
)
_sym_db.RegisterEnumDescriptor(_CHANNELTYPE)

ChannelType = enum_type_wrapper.EnumTypeWrapper(_CHANNELTYPE)
Invalid = 0
Joy7 = 17



_TBL_USER = _descriptor.Descriptor(
  name='Tbl_User',
  full_name='DB.Tbl_User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='DB.Tbl_User.uid', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channel', full_name='DB.Tbl_User.channel', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='registerTime', full_name='DB.Tbl_User.registerTime', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastLoginTime', full_name='DB.Tbl_User.lastLoginTime', index=3,
      number=4, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='loginTimes', full_name='DB.Tbl_User.loginTimes', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isLogin', full_name='DB.Tbl_User.isLogin', index=5,
      number=6, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='money1', full_name='DB.Tbl_User.money1', index=6,
      number=7, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='money2', full_name='DB.Tbl_User.money2', index=7,
      number=8, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg', full_name='DB.Tbl_User.msg', index=8,
      number=9, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='byteMsg', full_name='DB.Tbl_User.byteMsg', index=9,
      number=10, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=201,
)

DESCRIPTOR.message_types_by_name['Tbl_User'] = _TBL_USER
DESCRIPTOR.enum_types_by_name['ChannelType'] = _CHANNELTYPE

Tbl_User = _reflection.GeneratedProtocolMessageType('Tbl_User', (_message.Message,), dict(
  DESCRIPTOR = _TBL_USER,
  __module__ = 'db_pb2'
  # @@protoc_insertion_point(class_scope:DB.Tbl_User)
  ))
_sym_db.RegisterMessage(Tbl_User)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\010protocolB\002DB'))
# @@protoc_insertion_point(module_scope)
