# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import command_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='login.proto',
  package='Login',
  serialized_pb='\n\x0blogin.proto\x12\x05Login\x1a\rcommand.proto\"[\n\x08Register\x12\"\n\x04type\x18\x01 \x02(\x0e\x32\x14.Command.ServiceType\x12+\n\x07\x63hannel\x18\x02 \x02(\x0e\x32\x12.Command.ChannelID:\x06Normal\"9\n\x10RegisterResponse\x12%\n\terrorCode\x18\x01 \x02(\x0e\x32\x12.Command.ErrorCodeB\x11\n\x08protocolB\x05Login')




_REGISTER = _descriptor.Descriptor(
  name='Register',
  full_name='Login.Register',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Login.Register.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channel', full_name='Login.Register.channel', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=37,
  serialized_end=128,
)


_REGISTERRESPONSE = _descriptor.Descriptor(
  name='RegisterResponse',
  full_name='Login.RegisterResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='errorCode', full_name='Login.RegisterResponse.errorCode', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=130,
  serialized_end=187,
)

_REGISTER.fields_by_name['type'].enum_type = command_pb2._SERVICETYPE
_REGISTER.fields_by_name['channel'].enum_type = command_pb2._CHANNELID
_REGISTERRESPONSE.fields_by_name['errorCode'].enum_type = command_pb2._ERRORCODE
DESCRIPTOR.message_types_by_name['Register'] = _REGISTER
DESCRIPTOR.message_types_by_name['RegisterResponse'] = _REGISTERRESPONSE

class Register(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REGISTER

  # @@protoc_insertion_point(class_scope:Login.Register)

class RegisterResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REGISTERRESPONSE

  # @@protoc_insertion_point(class_scope:Login.RegisterResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n\010protocolB\005Login')
# @@protoc_insertion_point(module_scope)
