# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc.proto',
  package='RPC',
  serialized_pb=_b('\n\trpc.proto\x12\x03RPC\"I\n\tRpcHeader\x12\x1d\n\x06server\x18\x01 \x02(\x0e\x32\r.RPC.ServerID\x12\x1d\n\x06method\x18\x02 \x02(\x0e\x32\r.RPC.MethodID*\x16\n\x08ServerID\x12\n\n\x06MASTER\x10\x01*\x1e\n\x08MethodID\x12\x12\n\x0eRegisterServer\x10\x01\x42\x0f\n\x08protocolB\x03RPC')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_SERVERID = _descriptor.EnumDescriptor(
  name='ServerID',
  full_name='RPC.ServerID',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MASTER', index=0, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=93,
  serialized_end=115,
)
_sym_db.RegisterEnumDescriptor(_SERVERID)

ServerID = enum_type_wrapper.EnumTypeWrapper(_SERVERID)
_METHODID = _descriptor.EnumDescriptor(
  name='MethodID',
  full_name='RPC.MethodID',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RegisterServer', index=0, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=117,
  serialized_end=147,
)
_sym_db.RegisterEnumDescriptor(_METHODID)

MethodID = enum_type_wrapper.EnumTypeWrapper(_METHODID)
MASTER = 1
RegisterServer = 1



_RPCHEADER = _descriptor.Descriptor(
  name='RpcHeader',
  full_name='RPC.RpcHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='server', full_name='RPC.RpcHeader.server', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='method', full_name='RPC.RpcHeader.method', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=91,
)

_RPCHEADER.fields_by_name['server'].enum_type = _SERVERID
_RPCHEADER.fields_by_name['method'].enum_type = _METHODID
DESCRIPTOR.message_types_by_name['RpcHeader'] = _RPCHEADER
DESCRIPTOR.enum_types_by_name['ServerID'] = _SERVERID
DESCRIPTOR.enum_types_by_name['MethodID'] = _METHODID

RpcHeader = _reflection.GeneratedProtocolMessageType('RpcHeader', (_message.Message,), dict(
  DESCRIPTOR = _RPCHEADER,
  __module__ = 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:RPC.RpcHeader)
  ))
_sym_db.RegisterMessage(RpcHeader)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\010protocolB\003RPC'))
# @@protoc_insertion_point(module_scope)
